# fly.toml file generated for shindaggers on 2023-04-02T18:27:54-07:00

app = "shindaggers"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sjc"
processes = []

[env]
  BASE_URL = "https://shindaggers.io"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
