//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Editions = newEditionsTable("sd", "editions", "")

type editionsTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnInteger
	Name      mysql.ColumnString
	CreatedAt mysql.ColumnTimestamp
	UpdatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type EditionsTable struct {
	editionsTable

	NEW editionsTable
}

// AS creates new EditionsTable with assigned alias
func (a EditionsTable) AS(alias string) *EditionsTable {
	return newEditionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EditionsTable with assigned schema name
func (a EditionsTable) FromSchema(schemaName string) *EditionsTable {
	return newEditionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EditionsTable with assigned table prefix
func (a EditionsTable) WithPrefix(prefix string) *EditionsTable {
	return newEditionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EditionsTable with assigned table suffix
func (a EditionsTable) WithSuffix(suffix string) *EditionsTable {
	return newEditionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEditionsTable(schemaName, tableName, alias string) *EditionsTable {
	return &EditionsTable{
		editionsTable: newEditionsTableImpl(schemaName, tableName, alias),
		NEW:           newEditionsTableImpl("", "new", ""),
	}
}

func newEditionsTableImpl(schemaName, tableName, alias string) editionsTable {
	var (
		IDColumn        = mysql.IntegerColumn("id")
		NameColumn      = mysql.StringColumn("name")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		UpdatedAtColumn = mysql.TimestampColumn("updated_at")
		allColumns      = mysql.ColumnList{IDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = mysql.ColumnList{NameColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return editionsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
