//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type FightOutcomesOutcome string

const (
	FightOutcomesOutcome_Win  FightOutcomesOutcome = "win"
	FightOutcomesOutcome_Loss FightOutcomesOutcome = "loss"
	FightOutcomesOutcome_Draw FightOutcomesOutcome = "draw"
)

func (e *FightOutcomesOutcome) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "win":
		*e = FightOutcomesOutcome_Win
	case "loss":
		*e = FightOutcomesOutcome_Loss
	case "draw":
		*e = FightOutcomesOutcome_Draw
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for FightOutcomesOutcome enum")
	}

	return nil
}

func (e FightOutcomesOutcome) String() string {
	return string(e)
}
