//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ImageUploads struct {
	UserID     *int64
	ImageID    int64 `sql:"primary_key"`
	Path       *string
	Uploadname *string
	UploadedAt *time.Time
}
