//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type KnifeOwnershipTransType string

const (
	KnifeOwnershipTransType_Pull  KnifeOwnershipTransType = "pull"
	KnifeOwnershipTransType_Trade KnifeOwnershipTransType = "trade"
)

func (e *KnifeOwnershipTransType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "pull":
		*e = KnifeOwnershipTransType_Pull
	case "trade":
		*e = KnifeOwnershipTransType_Trade
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for KnifeOwnershipTransType enum")
	}

	return nil
}

func (e KnifeOwnershipTransType) String() string {
	return string(e)
}
