//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type KnifeOwnership struct {
	UserID        *int64
	KnifeID       *int64
	TransType     *KnifeOwnershipTransType
	TransactedAt  *time.Time
	InstanceID    int64 `sql:"primary_key"`
	WasSubscriber *bool
	IsVerified    *bool
	EditionID     *int32
}
