//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Knives struct {
	ID         int64 `sql:"primary_key"`
	Name       *string
	AuthorID   *int64
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
	Rarity     *KnivesRarity
	ImageName  *string
	Deleted    *bool
	ApprovedBy *int64
	ApprovedAt *time.Time
}
