//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Pullconfig struct {
	CommunityID int64            `sql:"primary_key"`
	Rarity      PullconfigRarity `sql:"primary_key"`
	Weight      *int32
	UpdatedAt   *time.Time
}
