//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CollectableInstances struct {
	ID            int64 `sql:"primary_key"`
	CollectableID int64
	OwnerID       int64
	EditionID     int64
	CreatedAt     time.Time
	DeletedAt     *time.Time
	Tags          *string
}
