//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Collectables struct {
	ID           int64 `sql:"primary_key"`
	Name         string
	CollectionID *int64
	CreatorID    int64
	Rarity       string
	Imagepath    string
	ApprovedAt   *time.Time
	ApprovedBy   *int64
	CreatedAt    time.Time
	DeletedAt    *time.Time
}
